server:
  port: ${APP_PORT:8081}
spring:
  application:
    name: tt-user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tt_user
    username: test
    password: ${DB_PG_PWD}
services:
  task-service-url: http://localhost:8080